export type TApplic = {
    "user_id": number,
    "fio": string,
    "fio_eng": string,
    "birth_date": string,
    "sex": string,
    "post_address": string,
    "email": string,
    "phones": string,
    "edu_institute": string,
    "edu_institute_address": string,
    "edu_specialization": string,
    "uch_stepen": string,
    "work_company": string,
    "work_start_year": number,
    "work_department": string,
    "work_position": string,
    "work_specialization": string,
    "public_organizations": string,
    "antok_city": string,
    "science_interests": string,
    "conf_topic": string,
    "conf_section": string,
    "conf_coauthors": string,
    "participation_type": string,
    "created_at": string,
    "updated_at": string,
    "need_compensation": boolean,
    "inn": string,
    "snils": string,
    "registration": string,
    "phone_work": string,
    "phone_home": string,
    "uch_zvanie": string,
    "work_city": string,
    "work_country": string,
    "acad_position": string,
    "work_company_short": string,
    "need_hotel": string,
    "birth_year": number
}


