name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install npm dependencies
        run: npm install
        
      - name: Install npm dependencies client
        working-directory: /home/runner/work/antok-conference/antok-conference/client
        run: npm install
        
      - name: Run build task
        run: npm run build --if-present
        
      - name: Deploy to Server 1
        env:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.HOST_DNS }}
            REMOTE_USER: ${{ secrets.USER_NAME }}
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/github-actions-key && chmod 600 ~/.ssh/github-actions-key
            cat >>~/.ssh/config <<END
            Host ec2
              HostName $REMOTE_HOST
              User $REMOTE_USER
              IdentityFile ~/.ssh/github-actions-key
              StrictHostKeyChecking no 
            END '
              cd /home/ubuntu/antok-conference && 
              git checkout main && 
              git fetch --all && 
              git reset --hard origin/main && 
              git pull origin main
            '




